- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars
  tags:
    - yumcron
    - always

- name: Install {{ yumcron_package_name }}
  yum:
    name: "{{ yumcron_package_name }}"
    state: latest
  tags:
    - yumcron

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    mode: '0644'
  loop: "{{ yumcron_config_files }}"
  tags:
    - yumcron
    - yumcron_config

- name: Start and enable yum-cron
  service:
    name: "{{ yumcron_service_name }}"
    state: started
    enabled: yes
  tags:
    - yumcron
