- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - yumcron
    - always

- name: Install yum-cron
  yum:
    name: yum-cron
    state: latest
  tags:
    - yumcron

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ yumcron_config_files }}"
  tags:
    - yumcron
    - yumcron_config

- name: Start and enable yum-cron
  service:
    name: yum-cron
    state: started
    enabled: true
  tags:
    - yumcron
